name: Build spec

permissions:
  contents: write

on: [pull_request, push]

jobs:
  build:
    name: Build
    container: dominik0int/sphinx
    runs-on: [self-hosted, linux]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt

      - name: Build PDF
        run: |
          make html
          sphinx-build -b latex docs build/latex
          make -C build/latex

      - uses: actions/upload-artifact@v2
        with:
          name: interbtc-spec
          path: build/latex/interbtc.pdf
          if-no-files-found: error

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/html/
          force_orphan: true
